package test:relay@0.1.0;

/// Passes a u32 through, adding `add` (default 0).
world relay {
    export node: interface {
        record inputs {
            in: u32,
            add: option<u32>,
        }
        record outputs {
            out: u32,
        }
        run: func(inputs: inputs) -> outputs;
    }
}
